spring:
  application:
    name: boardgames
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  flyway:
    out-of-order: true

security:
  jwt:
    secret: ${JWT_SECRET}
    expiration-minutes: 60